const CELLAR_ADDON_HOST = process.env.CELLAR_ADDON_HOST;
const CELLAR_ADDON_KEY_ID = process.env.CELLAR_ADDON_KEY_ID;
const CELLAR_ADDON_KEY_SECRET = process.env.CELLAR_ADDON_KEY_SECRET;
const CELLAR_BUCKET_NAME = process.env.CELLAR_BUCKET_NAME;

module.exports = {
  CELLAR_BUCKET_NAME,
  CELLAR_ADDON_KEY_SECRET,
  CELLAR_ADDON_KEY_ID,
  CELLAR_ADDON_HOST,
};
